language: generic

sudo : required
services:
  - docker

before_install:
  - docker build -t grafviktor/frontend-docker -f Dockerfile.dev .

script:
  # Explanation -e CI=true: The test command will force Jest to run in CI-mode, and tests will only run once instead of launching the watcher.
  - docker run -e CI=true grafviktor/frontend-docker npm run test