version: '3'
services:
    node-app: # Произвольное имя сервиса, это его же URL
        restart: always
        build:
            context: . # Используем собственный Dockerfile для сборки образа
        ports:
            - "8080:80" # Знак '-' означает объявление массива. Синтаксис: внешне-доступный_порт:порт_внутри_образа