version: '3'
services:
    node-app: # Произвольное имя сервиса, это его же URL
        restart: always
        build:
            context: . # Используем собственный Dockerfile для сборки образа
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./src:/app/src
        ports:
            - "8080:3000" # Знак '-' означает объявление массива. Синтаксис: внешне-доступный_порт:порт_внутри_образа